### ISSUE TITLE
Evil's Operators aren't picking up on the "inclusive" and "exclusive" modifiers when its commands are run from inside Evil-Hop-Hop

### ISSUE THREAD

**Issue by 3e33** [3e33/evil-hop#2]
Normally if you run something like `d2e` Evil will delete 2 words including the end character of the word, in contrast running `d<SPC>2e` (for Evil-Hop bound to space) will keep the last character.

Find out why this is happening.

**Comment by 3e33** [comment]
Fixed for operators, Visual state still needs work.

**Comment by Alexander-Shukaev** [comment]
What's wrong with https://github.com/PythonNut/evil-easymotion?

**Comment by 3e33** [comment]
That's not really relevant to this issue, you can open another ticket if you want to discuss things like that, thanks.

**Comment by Alexander-Shukaev** [comment]
You should make interactive calls to commands.

**Comment by 3e33** [comment]
It doesn't matter what call you make, it doesn't pick up `:type` as long as it's being called within another function. You can call it with anything.

**Comment by 3e33** [comment]
A bit of progress:

Using `evil-set-type 'command-here`, seems to be a step closer, unfortunately if this is run after an operator has already been set the new `:type` is used only on the _next_ call, so it lags behind. Maybe some way to reset the operator after setting a new type?
